language: csharp
mono: none
dotnet: 2.0.0
script:
 - dotnet restore
 - dotnet test TestUnitForAsyncLazy
 - dotnet pack AsyncLazy -c Release -o nupkgs
after_success:
 - test $TRAVIS_BRANCH = "master" && dotnet nuget push -s https://www.nuget.org -k $NUGET_API_KEY AsyncLazy/nupkgs/AsyncLazy.*.nupkg